ignores:
  [
    '@commitlint/*',
    '@typescript-eslint/*',
    'commitizen',
    'depcheck',
    'prettier',
    'prettier-*',
    'autoprefixer',
    'postcss',
    'tailwindcss',
    'tailwindcss-animated',
    '@rollup/rollup-linux-x64-gnu',
    '@esbuild/linux-x64',
  ]
skip-missing: true
